export const CATEGORIES = [
  { id: "sit", name: "Sit", icon: "textures/emotes/sit/sit_1", count: 28 },
  { id: "slp", name: "Sleep", icon: "textures/emotes/sleep/sleep_1", count: 24 },
  { id: "stn", name: "Stand", icon: "textures/emotes/stand/stand_1", count: 24 },
  { id: "act", name: "Action", icon: "textures/emotes/action/action_1", count: 24 },
  { id: "dnc", name: "Dance", icon: "textures/emotes/dance/dance_1", count: 5 },
];

export const EMOTES = [
  // --- SIT EMOTES ---
  { category: "sit", name: "Classic Sit", anim: "animation.humanoid.e.sit_1", icon: "textures/emotes/sit/sit_1" },
  { category: "sit", name: "Relaxed Sit", anim: "animation.humanoid.e.sit_2", icon: "textures/emotes/sit/sit_2" },
  { category: "sit", name: "Thinking Sit", anim: "animation.humanoid.e.sit_3", icon: "textures/emotes/sit/sit_3" },
  { category: "sit", name: "Casual Sit", anim: "animation.humanoid.e.sit_4", icon: "textures/emotes/sit/sit_4" },
  { category: "sit", name: "Crossed Sit", anim: "animation.humanoid.e.sit_5", icon: "textures/emotes/sit/sit_5" },
  { category: "sit", name: "Casual Sit 2", anim: "animation.humanoid.e.sit_6", icon: "textures/emotes/sit/sit_6" },
  { category: "sit", name: "Crossed Sit 2", anim: "animation.humanoid.e.sit_7", icon: "textures/emotes/sit/sit_7" },
  { category: "sit", name: "Chill Sit", anim: "animation.humanoid.e.sit_8", icon: "textures/emotes/sit/sit_8" },
  { category: "sit", name: "Deep Squat", anim: "animation.humanoid.e.sit_9", icon: "textures/emotes/sit/sit_9" },
  { category: "sit", name: "Cozy Sit", anim: "animation.humanoid.e.sit_10", icon: "textures/emotes/sit/sit_10" },
  { category: "sit", name: "Bored Sit", anim: "animation.humanoid.e.sit_11", icon: "textures/emotes/sit/sit_11" },
  { category: "sit", name: "Chill Sit 2", anim: "animation.humanoid.e.sit_12", icon: "textures/emotes/sit/sit_12" },
  { category: "sit", name: "Polite Sit", anim: "animation.humanoid.e.sit_13", icon: "textures/emotes/sit/sit_13" },
  { category: "sit", name: "Polite Sit 2", anim: "animation.humanoid.e.sit_14", icon: "textures/emotes/sit/sit_14" },
  { category: "sit", name: "Polite Sit 3", anim: "animation.humanoid.e.sit_15", icon: "textures/emotes/sit/sit_15" },
  { category: "sit", name: "Casual Sit 3", anim: "animation.humanoid.e.sit_16", icon: "textures/emotes/sit/sit_16" },
  { category: "sit", name: "Inspect Sit", anim: "animation.humanoid.e.sit_17", icon: "textures/emotes/sit/sit_17" },
  { category: "sit", name: "Meditate Sit", anim: "animation.humanoid.e.sit_18", icon: "textures/emotes/sit/sit_18" },
  { category: "sit", name: "Chill Sit 3", anim: "animation.humanoid.e.sit_19", icon: "textures/emotes/sit/sit_19" },
  { category: "sit", name: "Boss Sit", anim: "animation.humanoid.e.sit_20", icon: "textures/emotes/sit/sit_20" },
  { category: "sit", name: "Lounge Sit", anim: "animation.humanoid.e.sit_21", icon: "textures/emotes/sit/sit_21" },
  { category: "sit", name: "Chill Sit 4", anim: "animation.humanoid.e.sit_22", icon: "textures/emotes/sit/sit_22" },
  { category: "sit", name: "Relaxed Sit 2", anim: "animation.humanoid.e.sit_23", icon: "textures/emotes/sit/sit_23" },
  { category: "sit", name: "Comfy Sit", anim: "animation.humanoid.e.sit_24", icon: "textures/emotes/sit/sit_24" },
  { category: "sit", name: "Polite Sit 4", anim: "animation.humanoid.e.sit_25", icon: "textures/emotes/sit/sit_25" },
  { category: "sit", name: "Curled Sit", anim: "animation.humanoid.e.sit_26", icon: "textures/emotes/sit/sit_26" },
  { category: "sit", name: "Resting Sit", anim: "animation.humanoid.e.sit_27", icon: "textures/emotes/sit/sit_27" },
  { category: "sit", name: "Elegant Sit", anim: "animation.humanoid.e.sit_28", icon: "textures/emotes/sit/sit_28" },

  // --- SLEEP EMOTES ---
  { category: "slp", name: "Classic Sleep", anim: "animation.humanoid.e.sleep_1", icon: "textures/emotes/sleep/sleep_1" },
  { category: "slp", name: "Relaxed Sleep", anim: "animation.humanoid.e.sleep_2", icon: "textures/emotes/sleep/sleep_2" },
  { category: "slp", name: "Cozy Sleep", anim: "animation.humanoid.e.sleep_3", icon: "textures/emotes/sleep/sleep_3" },
  { category: "slp", name: "Star Sleep", anim: "animation.humanoid.e.sleep_4", icon: "textures/emotes/sleep/sleep_4" },
  { category: "slp", name: "Side Sleep", anim: "animation.humanoid.e.sleep_5", icon: "textures/emotes/sleep/sleep_5" },
  { category: "slp", name: "Faceplant", anim: "animation.humanoid.e.sleep_6", icon: "textures/emotes/sleep/sleep_6" },
  { category: "slp", name: "Lie Prone", anim: "animation.humanoid.e.sleep_7", icon: "textures/emotes/sleep/sleep_7" },
  { category: "slp", name: "Playful Sleep", anim: "animation.humanoid.e.sleep_8", icon: "textures/emotes/sleep/sleep_8" },
  { category: "slp", name: "Lounge Sleep", anim: "animation.humanoid.e.sleep_9", icon: "textures/emotes/sleep/sleep_9" },
  { category: "slp", name: "Lazy Sleep", anim: "animation.humanoid.e.sleep_10", icon: "textures/emotes/sleep/sleep_10" },
  { category: "slp", name: "Pillow Sleep", anim: "animation.humanoid.e.sleep_11", icon: "textures/emotes/sleep/sleep_11" },
  { category: "slp", name: "Turning Sleep", anim: "animation.humanoid.e.sleep_12", icon: "textures/emotes/sleep/sleep_12" },
  { category: "slp", name: "Messy Sleep", anim: "animation.humanoid.e.sleep_13", icon: "textures/emotes/sleep/sleep_13" },
  { category: "slp", name: "Messy Sleep 2", anim: "animation.humanoid.e.sleep_14", icon: "textures/emotes/sleep/sleep_14" },
  { category: "slp", name: "Exhausted Sleep", anim: "animation.humanoid.e.sleep_15", icon: "textures/emotes/sleep/sleep_15" },
  { category: "slp", name: "Restless Sleep", anim: "animation.humanoid.e.sleep_16", icon: "textures/emotes/sleep/sleep_16" },
  { category: "slp", name: "Chill Sleep", anim: "animation.humanoid.e.sleep_17", icon: "textures/emotes/sleep/sleep_17" },
  { category: "slp", name: "Reaching Sleep", anim: "animation.humanoid.e.sleep_18", icon: "textures/emotes/sleep/sleep_18" },
  { category: "slp", name: "Chill Sleep 2", anim: "animation.humanoid.e.sleep_19", icon: "textures/emotes/sleep/sleep_19" },
  { category: "slp", name: "Casual Sleep", anim: "animation.humanoid.e.sleep_20", icon: "textures/emotes/sleep/sleep_20" },
  { category: "slp", name: "Messy Sleep 3", anim: "animation.humanoid.e.sleep_21", icon: "textures/emotes/sleep/sleep_21" },
  { category: "slp", name: "Chill Sleep 3", anim: "animation.humanoid.e.sleep_22", icon: "textures/emotes/sleep/sleep_22" },
  { category: "slp", name: "Sprawled Sleep", anim: "animation.humanoid.e.sleep_23", icon: "textures/emotes/sleep/sleep_23" },
  { category: "slp", name: "Dreamy Sleep", anim: "animation.humanoid.e.sleep_24", icon: "textures/emotes/sleep/sleep_24" },

  // --- STAND POSES ---
  { category: "stn", name: "Pointing", anim: "animation.humanoid.e.stand_1", icon: "textures/emotes/stand/stand_1" },
  { category: "stn", name: "Wave", anim: "animation.humanoid.e.stand_2", icon: "textures/emotes/stand/stand_2" },
  { category: "stn", name: "Hips", anim: "animation.humanoid.e.stand_3", icon: "textures/emotes/stand/stand_3" },
  { category: "stn", name: "Pocket", anim: "animation.humanoid.e.stand_4", icon: "textures/emotes/stand/stand_4" },
  { category: "stn", name: "Crossed Arms", anim: "animation.humanoid.e.stand_5", icon: "textures/emotes/stand/stand_5" },
  { category: "stn", name: "Confident", anim: "animation.humanoid.e.stand_6", icon: "textures/emotes/stand/stand_6" },
  { category: "stn", name: "Guard Pose", anim: "animation.humanoid.e.stand_7", icon: "textures/emotes/stand/stand_7" },
  { category: "stn", name: "Battle Stance", anim: "animation.humanoid.e.stand_8", icon: "textures/emotes/stand/stand_8" },
  { category: "stn", name: "Fist Bump", anim: "animation.humanoid.e.stand_9", icon: "textures/emotes/stand/stand_9" },
  { category: "stn", name: "Ready Stance", anim: "animation.humanoid.e.stand_10", icon: "textures/emotes/stand/stand_10" },
  { category: "stn", name: "Braced", anim: "animation.humanoid.e.stand_11", icon: "textures/emotes/stand/stand_11" },
  { category: "stn", name: "Sword Rest", anim: "animation.humanoid.e.stand_12", icon: "textures/emotes/stand/stand_12" },
  { category: "stn", name: "Lean", anim: "animation.humanoid.e.stand_13", icon: "textures/emotes/stand/stand_13" },
  { category: "stn", name: "Defiant", anim: "animation.humanoid.e.stand_14", icon: "textures/emotes/stand/stand_14" },
  { category: "stn", name: "Hero Stance", anim: "animation.humanoid.e.stand_15", icon: "textures/emotes/stand/stand_15" },
  { category: "stn", name: "Check Item", anim: "animation.humanoid.e.stand_16", icon: "textures/emotes/stand/stand_16" },
  { category: "stn", name: "Random Stance", anim: "animation.humanoid.e.stand_17", icon: "textures/emotes/stand/stand_17" },
  { category: "stn", name: "Respect", anim: "animation.humanoid.e.stand_18", icon: "textures/emotes/stand/stand_18" },
  { category: "stn", name: "Thinking", anim: "animation.humanoid.e.stand_19", icon: "textures/emotes/stand/stand_19" },
  { category: "stn", name: "Lean 2", anim: "animation.humanoid.e.stand_20", icon: "textures/emotes/stand/stand_20" },
  { category: "stn", name: "Knee Rest", anim: "animation.humanoid.e.stand_21", icon: "textures/emotes/stand/stand_21" },
  { category: "stn", name: "Guard 2", anim: "animation.humanoid.e.stand_22", icon: "textures/emotes/stand/stand_22" },
  { category: "stn", name: "Sword Draw", anim: "animation.humanoid.e.stand_23", icon: "textures/emotes/stand/stand_23" },
  { category: "stn", name: "Head Rest", anim: "animation.humanoid.e.stand_24", icon: "textures/emotes/stand/stand_24" },

  // --- ACTION EMOTES ---
  { category: "act", name: "Applause", anim: "animation.humanoid.e.action_1", icon: "textures/emotes/action/action_1" },
  { category: "act", name: "Guide Way", anim: "animation.humanoid.e.action_2", icon: "textures/emotes/action/action_2" },
  { category: "act", name: "Stretching", anim: "animation.humanoid.e.action_3", icon: "textures/emotes/action/action_3" },
  { category: "act", name: "Power Pose", anim: "animation.humanoid.e.action_4", icon: "textures/emotes/action/action_4" },
  { category: "act", name: "All Fours", anim: "animation.humanoid.e.action_5", icon: "textures/emotes/action/action_5" },
  { category: "act", name: "Baby Mode", anim: "animation.humanoid.e.action_6", icon: "textures/emotes/action/action_6" },
  { category: "act", name: "Heavy Slam", anim: "animation.humanoid.e.action_7", icon: "textures/emotes/action/action_7" },
  { category: "act", name: "Leap", anim: "animation.humanoid.e.action_8", icon: "textures/emotes/action/action_8" },
  { category: "act", name: "Weapon Float", anim: "animation.humanoid.e.action_9", icon: "textures/emotes/action/action_9" },
  { category: "act", name: "Jump Kick", anim: "animation.humanoid.e.action_10", icon: "textures/emotes/action/action_10" },
  { category: "act", name: "Leap Slash", anim: "animation.humanoid.e.action_11", icon: "textures/emotes/action/action_11" },
  { category: "act", name: "Air Slash", anim: "animation.humanoid.e.action_12", icon: "textures/emotes/action/action_12" },
  { category: "act", name: "Wall Vault", anim: "animation.humanoid.e.action_13", icon: "textures/emotes/action/action_13" },
  { category: "act", name: "Air Drift", anim: "animation.humanoid.e.action_14", icon: "textures/emotes/action/action_14" },
  { category: "act", name: "Sleep Hover", anim: "animation.humanoid.e.action_15", icon: "textures/emotes/action/action_15" },
  { category: "act", name: "Shy Action", anim: "animation.humanoid.e.action_16", icon: "textures/emotes/action/action_16" },
  { category: "act", name: "Fall", anim: "animation.humanoid.e.action_17", icon: "textures/emotes/action/action_17" },
  { category: "act", name: "Fall 2", anim: "animation.humanoid.e.action_18", icon: "textures/emotes/action/action_18" },
  { category: "act", name: "Aerial Float", anim: "animation.humanoid.e.action_19", icon: "textures/emotes/action/action_19" },
  { category: "act", name: "Hero Fly", anim: "animation.humanoid.e.action_20", icon: "textures/emotes/action/action_20" },
  { category: "act", name: "Worm", anim: "animation.humanoid.e.action_21", icon: "textures/emotes/action/action_21" },
  { category: "act", name: "Twerk", anim: "animation.humanoid.e.action_22", icon: "textures/emotes/action/action_22" },
  { category: "act", name: "Combat", anim: "animation.humanoid.e.action_23", icon: "textures/emotes/action/action_23" },
  { category: "act", name: "Combat 2", anim: "animation.humanoid.e.action_24", icon: "textures/emotes/action/action_24" },

  // --- DANCE EMOTES ---
  { category: "dnc", name: "Oddloop Dance", anim: "animation.humanoid.e.oddloop", icon: "textures/emotes/dance/dance_1" },
  { category: "dnc", name: "Kicaw Dance", anim: "animation.humanoid.e.kicaw", icon: "textures/emotes/dance/dance_2" },
  { category: "dnc", name: "Pangya Dance", anim: "animation.humanoid.e.pangya", icon: "textures/emotes/dance/dance_3" },
  { category: "dnc", name: "Shigure Ui Dance", anim: "animation.humanoid.e.shigure_ui", icon: "textures/emotes/dance/dance_4" },
  { category: "dnc", name: "Sway Dance", anim: "animation.humanoid.e.sway", icon: "textures/emotes/dance/dance_5" },
];
