export const ITEM_TOTAL_PROPERTY = "kiw:all_stacker_item_total"
export const ITEM_EXPIRY_PROPERTY = "kiw:all_stacker_item_expiry"
export const ITEM_DISPLAY_PROPERTY = "kiw:all_stacker_item_display"
export const MOB_TOTAL_PROPERTY = "kiw:all_stacker_mob_total"
export const MOB_DISPLAY_PROPERTY = "kiw:all_stacker_mob_display"
export const ITEM_SUPPRESS_TAG = "kiw_all_stacker_item_suppress"
export const MOB_SUPPRESS_TAG = "kiw_all_stacker_mob_suppress"

const ITEM_ENTITY_TYPE = "minecraft:item"
const STACKER_LABEL_PREFIX = "§e×"

function readDynamicProperty(entity, key) {
 try {
  return entity?.getDynamicProperty?.(key)
 } catch {
  return undefined
 }
}

function removeDynamicProperty(entity, key) {
 try {
  entity?.setDynamicProperty?.(key, undefined)
 } catch {
 }
}

function readItemStack(entity) {
 try {
  return entity?.getComponent?.(ITEM_ENTITY_TYPE)?.itemStack
 } catch {
  return undefined
 }
}

function readNameTag(entity) {
 try {
  return entity?.nameTag || ""
 } catch {
  return ""
 }
}

export function isItemEntity(entity) {
 return entity?.typeId === ITEM_ENTITY_TYPE
}

/**
 * Detects the display label generated by All Stacker.
 * A manually renamed entity must remain protected from ClearLag.
 */
function nameTagIsStackerLabel(entity) {
 return readNameTag(entity).startsWith(STACKER_LABEL_PREFIX)
}

export function hasStackerItemMetadata(entity) {
 return readDynamicProperty(entity, ITEM_DISPLAY_PROPERTY) === true
}

export function hasStackerMobMetadata(entity) {
 return readDynamicProperty(entity, MOB_DISPLAY_PROPERTY) === true
}

export function hasStackerMetadata(entity) {
 return hasStackerItemMetadata(entity) || hasStackerMobMetadata(entity)
}

export function isStackerItemLabel(entity) {
 return hasStackerItemMetadata(entity) && nameTagIsStackerLabel(entity)
}

export function isStackerMobLabel(entity) {
 return hasStackerMobMetadata(entity) && nameTagIsStackerLabel(entity)
}

export function isStackerLabel(entity) {
 return isStackerItemLabel(entity) || isStackerMobLabel(entity)
}

export function getStackerItemTotal(entity, physicalAmount = 0) {
 const stored = Number(readDynamicProperty(entity, ITEM_TOTAL_PROPERTY))
 return Number.isSafeInteger(stored) && stored > physicalAmount ? stored : physicalAmount
}

export function getStackerMobTotal(entity) {
 const stored = Number(readDynamicProperty(entity, MOB_TOTAL_PROPERTY))
 return Number.isSafeInteger(stored) && stored > 1 ? stored : 1
}

export function getItemUnitCount(entity) {
 const physicalAmount = Number(readItemStack(entity)?.amount) || 0
 return getStackerItemTotal(entity, physicalAmount)
}

export function getStackedUnitCount(entity) {
 return isItemEntity(entity) ? getItemUnitCount(entity) : getStackerMobTotal(entity)
}

export function hasManualNameTag(entity) {
 if (readNameTag(entity).length === 0) return false
 return !isStackerLabel(entity)
}

export function hasRenamedItemStack(entity) {
 const itemStack = readItemStack(entity)
 try {
  return (itemStack?.nameTag || "").length > 0
 } catch {
  return false
 }
}

export function isNameProtected(entity) {
 if (isItemEntity(entity)) return hasRenamedItemStack(entity) || hasManualNameTag(entity)
 return hasManualNameTag(entity)
}

/**
 * Removes stack metadata before entity removal so All Stacker cannot restore it.
 * This also marks the entity with the appropriate suppression tag.
 */
export function releaseStackerMetadata(entity) {
 if (!hasStackerMetadata(entity)) return false
 try {
  entity.addTag(isItemEntity(entity) ? ITEM_SUPPRESS_TAG : MOB_SUPPRESS_TAG)
 } catch {
 }
 removeDynamicProperty(entity, ITEM_TOTAL_PROPERTY);
 removeDynamicProperty(entity, ITEM_EXPIRY_PROPERTY)
 removeDynamicProperty(entity, ITEM_DISPLAY_PROPERTY)
 removeDynamicProperty(entity, MOB_TOTAL_PROPERTY)
 removeDynamicProperty(entity, MOB_DISPLAY_PROPERTY)
 return true
}
